/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.salesdb.Quotes;
import com.salesdb.Reps;
import com.salesdb.Tasks;
import com.salesdb.service.RepsService;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class Reps.
 * @see Reps
 */
@RestController("salesdb.RepsController")
@RequestMapping("/salesdb/Reps")
@Api(description = "Exposes APIs to work with Reps resource.", value = "RepsController")
public class RepsController {

    private static final Logger LOGGER = LoggerFactory.getLogger(RepsController.class);

    @Autowired
    @Qualifier("salesdb.RepsService")
    private RepsService repsService;

    /**
     * @deprecated Use {@link #findReps(String, Pageable)} instead.
     */
    @Deprecated
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of Reps instances matching the search criteria.")
    public Page<Reps> findReps(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Reps list");
        return repsService.findAll(queryFilters, pageable);
    }

    @RequestMapping(method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of Reps instances matching the search criteria.")
    public Page<Reps> findReps(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Reps list");
        return repsService.findAll(query, pageable);
    }

    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @ApiOperation(value = "Returns downloadable file for the data.")
    public Downloadable exportReps(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return repsService.export(exportType, query, pageable);
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the total count of Reps instances.")
    public Long countReps(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting Reps");
        return repsService.count(query);
    }

    @RequestMapping(value = "/{id:.+}/taskses", method = RequestMethod.GET)
    @ApiOperation(value = "Gets the taskses instance associated with the given id.")
    public Page<Tasks> findAssociatedTaskses(Pageable pageable, @PathVariable("id") Integer id) {
        LOGGER.debug("Fetching all associated taskses");
        return repsService.findAssociatedTaskses(id, pageable);
    }

    @RequestMapping(value = "/{id:.+}/quoteses", method = RequestMethod.GET)
    @ApiOperation(value = "Gets the quoteses instance associated with the given id.")
    public Page<Quotes> findAssociatedQuoteses(Pageable pageable, @PathVariable("id") Integer id) {
        LOGGER.debug("Fetching all associated quoteses");
        return repsService.findAssociatedQuoteses(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service RepsService instance
	 */
    protected void setRepsService(RepsService service) {
        this.repsService = service;
    }

    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Creates a new Reps instance.")
    public Reps createReps(@RequestBody Reps reps) {
        LOGGER.debug("Create Reps with information: {}", reps);
        reps = repsService.create(reps);
        LOGGER.debug("Created Reps with information: {}", reps);
        return reps;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the Reps instance associated with the given id.")
    public Reps getReps(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Reps with id: {}", id);
        Reps foundReps = repsService.getById(id);
        LOGGER.debug("Reps details with id: {}", foundReps);
        return foundReps;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Updates the Reps instance associated with the given id.")
    public Reps editReps(@PathVariable(value = "id") Integer id, @RequestBody Reps reps) throws EntityNotFoundException {
        LOGGER.debug("Editing Reps with id: {}", reps.getId());
        reps.setId(id);
        reps = repsService.update(reps);
        LOGGER.debug("Reps details with id: {}", reps);
        return reps;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Deletes the Reps instance associated with the given id.")
    public boolean deleteReps(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Reps with id: {}", id);
        Reps deletedReps = repsService.delete(id);
        return deletedReps != null;
    }
}
