/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.Channels;
import com.salesdb.Reps;

/**
 * Service object for domain model class Channels.
 *
 * @see {@link Channels}
 */
public interface ChannelsService {

    /**
     * Creates a new Channels.
     *
     * @param channels The information of the created CompositeTable.
     * @return The created Channels.
     */
	Channels create(Channels channels);


	/**
	 * Finds Channels by id.
	 *
	 * @param channelsId The id of the wanted Channels.
	 * @return The found Channels. If no Channels is found, this method returns null.
	 */
	Channels getById(Integer channelsId) throws EntityNotFoundException;

    /**
	 * Finds Channels by unique key.
	 *
	 * @param Map of one of Unique key column fields vs values.
	 * @return The found Channels. If no Channels is found, this method returns null.
	 */
	Channels getByUniqueKey(Map<String, Object> uniqueyKeyFieldsVsValues) throws EntityNotFoundException;

	/**
	 * Updates the information of a Channels.
	 *
	 * @param channels The information of the updated Channels.
	 * @return The updated Channels.
     *
	 * @throws EntityNotFoundException if no Channels is found with given id.
	 */
	Channels update(Channels channels) throws EntityNotFoundException;

    /**
	 * Deletes a Channels.
	 *
	 * @param channelsId The id of the deleted Channels.
	 * @return The deleted Channels.
     *
	 * @throws EntityNotFoundException if no Channels is found with the given id.
	 */
	Channels delete(Integer channelsId) throws EntityNotFoundException;

	/**
	 * Finds all Channels.
	 *
	 * @return A list of Channels.
	 */
    @Deprecated
	Page<Channels> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Channels.
	 * @return A list of Channels.
	 */
    Page<Channels> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Channels in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Channels.
	 */
	long count(String query);

    Page<Reps> findAssociatedRepses(Integer id, Pageable pageable);

    Page<Channels> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

