/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.Leads;
import com.salesdb.Quotes;

/**
 * Service object for domain model class Leads.
 *
 * @see {@link Leads}
 */
public interface LeadsService {

    /**
     * Creates a new Leads.
     *
     * @param leads The information of the created CompositeTable.
     * @return The created Leads.
     */
	Leads create(Leads leads);


	/**
	 * Finds Leads by id.
	 *
	 * @param leadsId The id of the wanted Leads.
	 * @return The found Leads. If no Leads is found, this method returns null.
	 */
	Leads getById(Integer leadsId) throws EntityNotFoundException;

    /**
	 * Finds Leads by unique key.
	 *
	 * @param Map of one of Unique key column fields vs values.
	 * @return The found Leads. If no Leads is found, this method returns null.
	 */
	Leads getByUniqueKey(Map<String, Object> uniqueyKeyFieldsVsValues) throws EntityNotFoundException;

	/**
	 * Updates the information of a Leads.
	 *
	 * @param leads The information of the updated Leads.
	 * @return The updated Leads.
     *
	 * @throws EntityNotFoundException if no Leads is found with given id.
	 */
	Leads update(Leads leads) throws EntityNotFoundException;

    /**
	 * Deletes a Leads.
	 *
	 * @param leadsId The id of the deleted Leads.
	 * @return The deleted Leads.
     *
	 * @throws EntityNotFoundException if no Leads is found with the given id.
	 */
	Leads delete(Integer leadsId) throws EntityNotFoundException;

	/**
	 * Finds all Leads.
	 *
	 * @return A list of Leads.
	 */
    @Deprecated
	Page<Leads> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Leads.
	 * @return A list of Leads.
	 */
    Page<Leads> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Leads in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Leads.
	 */
	long count(String query);

    Page<Quotes> findAssociatedQuoteses(Integer id, Pageable pageable);

    Page<Leads> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

