/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.Sales;

/**
 * Service object for domain model class Sales.
 *
 * @see {@link Sales}
 */
public interface SalesService {

    /**
     * Creates a new Sales.
     *
     * @param sales The information of the created CompositeTable.
     * @return The created Sales.
     */
	Sales create(Sales sales);


	/**
	 * Finds Sales by id.
	 *
	 * @param salesId The id of the wanted Sales.
	 * @return The found Sales. If no Sales is found, this method returns null.
	 */
	Sales getById(Integer salesId) throws EntityNotFoundException;

    /**
	 * Finds Sales by unique key.
	 *
	 * @param Map of one of Unique key column fields vs values.
	 * @return The found Sales. If no Sales is found, this method returns null.
	 */
	Sales getByUniqueKey(Map<String, Object> uniqueyKeyFieldsVsValues) throws EntityNotFoundException;

	/**
	 * Updates the information of a Sales.
	 *
	 * @param sales The information of the updated Sales.
	 * @return The updated Sales.
     *
	 * @throws EntityNotFoundException if no Sales is found with given id.
	 */
	Sales update(Sales sales) throws EntityNotFoundException;

    /**
	 * Deletes a Sales.
	 *
	 * @param salesId The id of the deleted Sales.
	 * @return The deleted Sales.
     *
	 * @throws EntityNotFoundException if no Sales is found with the given id.
	 */
	Sales delete(Integer salesId) throws EntityNotFoundException;

	/**
	 * Finds all Sales.
	 *
	 * @return A list of Sales.
	 */
    @Deprecated
	Page<Sales> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Sales.
	 * @return A list of Sales.
	 */
    Page<Sales> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Sales in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Sales.
	 */
	long count(String query);


    Page<Sales> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

